from typing import Any, Optional, List, Dict
from enum import Enum
from pydantic import BaseModel, Field

class GateType(str, Enum):
    APPROVE = "Approval Required"
    REVIEW = "Review Needed"
    EDIT = "Editing Checkpoint"
    COMPLEX = "Complex Case"

class DecisionType(str, Enum):
    APPROVE = "Approve"
    DENY = "Deny"
    EDIT = "Edit"
    TAKEOVER = "Takeover"

class QueueItem(BaseModel):
    """An item placed in the human reviewer queue."""
    urgency: str = Field(description="Urgency tier: Low, Medium, High.")
    content_draft: str = Field(description="The primary content draft under review.")
    original_agent_output: str = Field(description="Raw original output generated by the AI agent.")
    sla_timer_sec: int = Field(description="SLA time limit in seconds for reviewer response.")
    context_summary: str = Field(description="Context summary explaining background info.")

class HumanDecision(BaseModel):
    """The decision and action provided by the human reviewer."""
    decision: DecisionType = Field(description="Reviewer's choice: Approve, Deny, Edit, or Takeover.")
    reviewer_feedback: Optional[str] = Field(default=None, description="Detailed feedback explaining why output was accepted/rejected.")
    edited_content: Optional[str] = Field(default=None, description="The modified text if the human decided to Edit.")
    takeover_reason: Optional[str] = Field(default=None, description="Log explaining why manual takeover was initiated.")

class FeedbackLog(BaseModel):
    """Logs captured to train and improve the AI agent's prompt/guidelines."""
    action: DecisionType = Field(description="The human decision type captured.")
    learning_points: str = Field(description="Key insights learned from the human's feedback or corrections.")
    guidelines_updated: str = Field(description="Updated prompt/guideline rules generated for future turns.")

class State(BaseModel):
    """State for the Human-in-the-Loop orchestrator."""
    query: str = Field(description="The overall task or prompt processed by the agent.")
    scenario: str = Field(default="approve", description="Active test scenario: 'approve', 'deny', 'edit', or 'takeover_fatigue'.")
    
    # HITL gate and queue items
    gate_identified: Optional[GateType] = None
    queue_item: Optional[QueueItem] = None
    human_decision: Optional[HumanDecision] = None
    feedback_log: Optional[FeedbackLog] = None
    
    # Reviewer fatigue & load balancing
    fatigue_score: float = 0.0  # 0.0 (fresh) to 1.0 (exhausted)
    load_action: str = "MAINTAIN"  # REDUCE or MAINTAIN
    automation_level: float = 0.5  # Base level 50% automated
    
    # Operational learning & reporting
    learned_patterns: str = ""
    final_report: Optional[str] = None

class Dependencies(BaseModel):
    """Injectable agent dependencies."""
    gate_agent: Any
    ui_agent: Any
    feedback_agent: Any
    fatigue_agent: Any
