from typing import Any, Optional, List, Dict
from enum import Enum
from pydantic import BaseModel, Field

class SplitType(str, Enum):
    FIXED = "Equal Size Chunks"
    SMART = "Natural Breaks"
    CONTEXT = "Keep Related Together"

class Document(BaseModel):
    """A document containing knowledge to index and search."""
    title: str = Field(description="The title of the source document.")
    content: str = Field(description="The full raw text content of the document.")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Metadata key-value pairs (e.g. author, date, type).")
    tags: List[str] = Field(default_factory=list, description="Tags or labels describing document topics.")

class Chunk(BaseModel):
    """A granular segmented text piece of a document."""
    text: str = Field(description="The text content of this chunk.")
    doc_title: str = Field(description="The title of the parent document.")
    index: int = Field(description="The index position of this chunk within the document.")
    start_char: int = Field(description="Start character index of this chunk in parent document.")
    end_char: int = Field(description="End character index of this chunk in parent document.")

class SearchResult(BaseModel):
    """A matched text chunk with its calculated relevance score."""
    chunk: Chunk = Field(description="The matched chunk retrieved from the database.")
    score: float = Field(description="Calculated relevance/similarity score (0.0 to 1.0).")

class RAGResponse(BaseModel):
    """The synthesized answer generated by the AI model grounded in sources."""
    answer: str = Field(description="The final synthesized answer answering the query.")
    citations: List[str] = Field(default_factory=list, description="Verifiable reference document titles/chunk indices.")
    is_good: bool = Field(description="Boolean checking if response quality, completeness, and confidence are high.")
    confidence_score: float = Field(description="Self-assessed confidence score of the generated answer (0.0 to 1.0).")

class State(BaseModel):
    """Memory state for the Knowledge Retrieval (RAG) orchestrator."""
    query: str = Field(description="The raw query/question asked by the user.")
    scenario: str = Field(default="happy_path", description="Active scenario: 'happy_path' or 'loop_path'.")
    
    # RAG pipeline elements
    documents: List[Document] = Field(default_factory=list, description="Loaded documents.")
    chunks: List[Chunk] = Field(default_factory=list, description="Segmented text chunks.")
    improved_query: str = Field(default="", description="Query expanded with related search terms.")
    retrieved_chunks: List[Chunk] = Field(default_factory=list, description="Matching chunks retrieved from query.")
    ranked_results: List[SearchResult] = Field(default_factory=list, description="Ranked and sorted results.")
    generated_response: Optional[RAGResponse] = Field(default=None, description="The final synthesized RAG answer.")
    
    # Control and evaluation parameters
    search_attempts: int = Field(default=1, description="Number of search/quality attempts performed.")
    max_attempts: int = Field(default=2, description="Max quality retry loop attempts limit.")
    retrieval_limit: int = Field(default=2, description="Target number of chunks to fetch during search.")
    
    # Metrics and reports
    accuracy_score: float = Field(default=0.0, description="Measured factual accuracy score.")
    coverage_score: float = Field(default=0.0, description="Measured complete information coverage score.")
    system_status: str = Field(default="Initializing", description="Current operations log detail.")
    final_report: Optional[str] = Field(default=None, description="Beautiful SRE performance report summary.")

class Dependencies(BaseModel):
    """Injectable dependencies for the RAG agents."""
    ingestion_agent: Any
    expansion_agent: Any
    ranking_agent: Any
    generation_agent: Any

