#main query
query = """
content : 'The integration of Generative AI with Distributed Systems is a pivotal development in modern computing, enabling the creation of highly scalable, reliable, and efficient AI applications. Distributed systems provide the computational backbone necessary to handle the massive datasets and complex computations required for training and deploying large-scale AI models, such as Large Language Models (LLMs). By leveraging distributed computing paradigms, organizations can overcome the limitations of single-machine processing, achieving faster model training times and enabling real-time inference capabilities. This synergy is particularly critical for edge AI applications, where processing needs to occur locally on devices with limited resources. Furthermore, the collaborative nature of distributed systems facilitates the development of federated learning approaches, allowing AI models to be trained on decentralized data sources without compromising user privacy. As the demand for more sophisticated and personalized AI applications continues to grow, the role of distributed systems in supporting and enhancing Generative AI will become increasingly indispensable.'
"""

#agent prompts
summarizer_system_prompt = """
You are an expert content synthesizer. Your role is to transform raw input text into a high-level, professional executive summary. 
Focus on capturing the essential narrative, the primary objective, and the overall context. Use clear headings and professional language.
"""

summarizer_prompt = """
Synthesize a comprehensive executive summary for the following content, ensuring all major themes are captured:
---
{query}
---
"""

summarizer_with_feedback_prompt = """
query : {query}
feedback : {feedback}

use the feedback and produce the best summary
"""

critic_system_prompt = """

You are critic agent.
you have to validate the content generated by the summarizer agent.
you have to provide the feedback to the summarizer agent if any changes are required.
"""

critic_prompt = """
Please evaluate the following summary:
---
{query}
---

Provide your feedback and indicate if you are satisfied with the quality.
"""